### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by benoitbayol**
size has to be a multiple of 3600

**Is this a bug fix or adding new feature?**
No

**What is this PR about? / Why do we need it?**
documentation update

**What testing is done?** 
None

### CODE REVIEW

**Comment by leakingtapan** [comment]
@benoitbayol you will need to sign the CLA to get PR merged

**Comment by benoitbayol** [comment]
Ok Will do it :)

**Comment by benoitbayol** [comment]
Not sure to understand why the CI did not pass :/

```
• Failure in Spec Setup (BeforeEach) [60.001 seconds]
AWS FSx for Lustre CSI Driver
/home/travis/gopath/src/github.com/kubernetes-sigs/aws-fsx-csi-driver/tests/sanity/sanity_test.go:55
  Controller Service
  /home/travis/gopath/pkg/mod/github.com/kubernetes-csi/csi-test@v0.3.0-2/pkg/sanity/tests.go:44
    DeleteVolume [BeforeEach]
    /home/travis/gopath/pkg/mod/github.com/kubernetes-csi/csi-test@v0.3.0-2/pkg/sanity/controller.go:448
      should fail when no volume id is provided
      /home/travis/gopath/pkg/mod/github.com/kubernetes-csi/csi-test@v0.3.0-2/pkg/sanity/controller.go:455
      Expected error:
          <*errors.errorString | 0xc00037ad90>: {
              s: "Connection timed out",
          }
          Connection timed out
      not to have occurred
      /home/travis/gopath/pkg/mod/github.com/kubernetes-csi/csi-test@v0.3.0-2/pkg/sanity/sanity.go:97
------------------------------
••E0430 19:29:02.354315   12736 driver.go:88] GRPC error: rpc error: code = InvalidArgument desc = Volume ID not provided
•E0430 19:29:02.355022   12736 driver.go:88] GRPC error: rpc error: code = InvalidArgument desc = Volume capabilities not provided
••E0430 19:29:02.357817   12736 driver.go:88] GRPC error: rpc error: code = NotFound desc = Volume not found
```

**Comment by benoitbayol** [comment]
Maybe a new trigger on the build will do ?  Since there is:
```
Connection timed out
      not to have occurred
```

**Pull request merged**
