### PR TITLE
chore: Bump chart version

### PR DESCRIPTION
**Pull request by toneill818**
**Is this a bug fix or adding new feature?**
Bump chart version which will include PR #377 

**What is this PR about? / Why do we need it?**
Creates a new release with the changes.
Issue #386 
**What testing is done?**

### CODE REVIEW

**Comment by jacobwolfaws** [comment]
@toneill818 you need to do your CLA Authorization.

/ok-to-test

**Comment by toneill818** [comment]
It looks like the e2e test failed due to an account limit in AWS. There may be an issue with cleaning up the fsx shares in that account unless it is used by other projects too. 

> failed to created filesystem CreateFileSystem failed: ServiceLimitExceeded: Account 209411653980 can create up to 100800 GiB of deployment type SCRATCH_1

**Pull request merged**
