### PR TITLE
upgrade kubernetes dependencies to v0.22.3

### PR DESCRIPTION
**Pull request by jacobwolfaws**
**Is this a bug fix or adding new feature?**
bug fix
**What is this PR about? / Why do we need it?**
updating kubernetes dependencies, corresponding packages and pack calls to move to v0.22.3. We're currently using a deprecated kubernetes version that contains known CVEs
**What testing is done?** 
manual

### CODE REVIEW

**Comment by olemarkus** [comment]
Any reason you stopped at 0.22.3?

**Comment by jacobwolfaws** [comment]
> Any reason you stopped at 0.22.3?

I chose 0.22.3 to keep us in line with the aws-efs-csi-driver + address known CVEs with 0.22.2 and below. I'm not opposed to updating the dependencies further, but that change would have a separate goal than this one.

**Comment by olemarkus** [comment]
Fair enough. I was looking to go for something higher, at least a supported k8s version, myself. I know 1.25 has some challenges due to ginkgo2 requirements, but at least 1.24 should be fine.

/lgtm
/approve

**Pull request merged**
