### PR TITLE
Split e2e into its own module

### PR DESCRIPTION
**Pull request by olemarkus**
Prevents global dependency on k8s/kubernetes, making deps managing a lot simpler. Also renamed the main module to follow the sigs.k8s.io convention.

### CODE REVIEW

**Comment by wongma7** [comment]
/hold

somebody si working on 0.8.3 right now so just checking to make sure they dont get surprised by this hgue pr merging

**Comment by olemarkus** [comment]
Just saw 0.8.3 released. Can we unhold this one now?

**Comment by olemarkus** [comment]
I assume this is now safe
/hold cancel

**Pull request merged**
